/*
LIST OF BEAMAGINE ERRORS
*/

#define L3CAM_OK    0

//!INTERNAL ERRORS
#define L3CAM_NO_SENSORS_AVAILABLE              21

#define L3CAM_TIMEOUT_ERROR                     210
#define L3CAM_ERROR_OUT_OF_MEMORY               211

#define L3CAM_UNDEFINED_LASER_CLASS             220
#define L3CAM_UNDEFINED_SENSOR                  222
#define L3CAM_VALUE_OUT_OF_RANGE                223
#define L3CAM_SENSOR_NOT_AVAILABLE              224

#define L3CAM_ERROR_CREATING_TCP_CLIENT_SOCKET  230
#define L3CAM_ERROR_INITALIZING_WSA             231
#define L3CAM_ERROR_CONNECTING_WITH_TCP_SERVER  232
#define L3CAM_ERROR_SENDING_TCP_MESSAGE         233
#define L3CAM_ERROR_CREATING_TCP_SERVER_SOCKET  234
#define L3CAM_ERROR_BINDING_SOCKET              235
#define L3CAM_ERROR_STARTING_TCP_SERVER         236
#define L3CAM_ERROR_ACCEPTING_TCP_CLIENT        237

//!LIDAR ERRORS


//!POLARIMETRIC ERRORS
#define ERROR_POL_STD_EXCEPTION             30
#define ERROR_POL_RUNTIME_EXCEPTION         31
#define ERROR_POL_GENERIC_EXCEPTION         32
#define ERROR_POL_TIMEOUT_EXCEPTION         33
#define ERROR_POL_UNDEFINED_ERROR           34
#define ERROR_POL_PERCEPTION_EXCEPTION      35

//!THERMAL ERRORS
#define ERROR_OPENING_THERMAL_CAMERA    40
#define ERROR_THERMAL_IMAGE_SIZE        41
#define ERROR_CLOSING_THERMAL_CAMERA    42
#define ERROR_SETTING_THERMAL_LUT       43
#define ERROR_GETTING_THERMAL_LUT       44
#define ERROR_SETTING_THERMAL_SHARPEN   45
#define ERROR_SETTING_THERMAL_SMOOTH    46
#define ERROR_GETTING_THERMAL_SYSTEM    47
#define ERROR_SETTING_THERMAL_SYSTEM    48

